# Generated by Django 4.2.7 on 2023-11-21 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='policia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=20)),
                ('edad', models.CharField(max_length=20)),
                ('cedula', models.CharField(max_length=20)),
                ('rango', models.CharField(max_length=20)),
                ('especialidad', models.CharField(max_length=50)),
            ],
        ),
    ]
