# Generated by Django 4.2.7 on 2023-11-22 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='rango',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=20, null=True)),
                ('area', models.CharField(max_length=50, null=True)),
                ('tiempo', models.IntegerField(max_length=20, null=True)),
                ('sector', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='policia',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
