# Generated by Django 4.2.7 on 2023-11-25 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policia', '0002_rango_policia_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policia',
            name='rango',
        ),
        migrations.AddField(
            model_name='policia',
            name='puesto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='policia.rango'),
        ),
        migrations.AlterField(
            model_name='rango',
            name='sector',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
