# Generated by Django 4.2.7 on 2023-11-26 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policia', '0003_remove_policia_rango_policia_puesto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=20)),
                ('nivel_academico', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='policia',
            name='especialidad',
        ),
        migrations.AddField(
            model_name='policia',
            name='especialista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='policia.especialidad'),
        ),
    ]
