# Generated by Django 4.2.7 on 2023-11-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policia', '0004_especialidad_remove_policia_especialidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidad',
            name='descripcion',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='nivel_academico',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='nombre',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='policia',
            name='apellidos',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='policia',
            name='cedula',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='policia',
            name='edad',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='policia',
            name='nombres',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
